### ISSUE TITLE
Combination.of(Arrays.asList(0,1,2,3,4,5,6,7,8,9),5) calls  java.lang.NullPointerException in Factorial.java:60

### ISSUE THREAD

**Issue by yujiaao** [raistlic/raistlic-lib-commons-core#1]
Combination.of(Arrays.asList(0,1,2,3,4,5,6,7,8,9),5)

Exception in thread "main" java.lang.NullPointerException
    at org.raistlic.common.permutation.Factorial.of(Factorial.java:60)
    at org.raistlic.common.permutation.Combination$DefaultAlgorithm.getCombinationCount(Combination.java:207)
    at org.raistlic.common.permutation.Combination.<init>(Combination.java:116)
    at org.raistlic.common.permutation.Combination.of(Combination.java:85)
    at org.raistlic.common.permutation.Combination.of(Combination.java:59)
    at NumMax.main(NumMax.java:25)

**Comment by yujiaao** [comment]
It was an error in version 1.3, in the version 1.4-SNAPSHOT it has fixed!
